<!-- Table Selection Overlay -->
<div id="mesas-overlay"
    class="fixed inset-0 bg-black/50 z-50  hidden flex items-center justify-center backdrop-blur-sm transition-opacity duration-300">
    <div class="bg-white rounded-sm shadow-2xl flex flex-col overflow-hidden animate-fade-in-up transform transition-all"
        style="width: 95vw; height: 95vh;">

        <!-- Header -->
        <div
            class="h-16  from-indigo-600 to-purple-600 text-gray-600 flex items-center justify-between px-6 pr-1 shadow-md shrink-0">
            <h2 class="text-2xl font-bold flex items-center gap-3">
                <span class="text-3xl">🍽️</span>
                <span>Selección de Mesa</span>
            </h2>
            <div class="flex items-center ">

                <button onclick="toggleMesasOverlay()"
                    class="border-2 border-red-400 bg-red-200 p-3 hover:bg-red-500/20 rounded-sm text-xl transition-colors focus:outline-none">
                    CERRAR
                </button>
            </div>
        </div>

        <!-- Content -->
        <div class="flex-1 flex overflow-hidden">
            <!-- Sidebar / Floors -->
            <div class="w-[100px] bg-gray-50 border-r border-gray-200 flex flex-col items-center py-6 gap-4 overflow-y-auto z-10 shadow-inner"
                id="pisos-nav">
                <!-- Tabs generated by JS -->
            </div>

            <!-- Map Area -->
            <div class="w-[calc(100%-100px)] bg-slate-100 relative overflow-auto p-0 cursor-grab active:cursor-grabbing"
                id="mesas-container">
                <!-- Grid Background -->

                <div class="absolute inset-0 flex items-center justify-center text-gray-400 z-0 content-loading">
                    <div class="flex flex-col items-center animate-pulse">
                        <span class="text-4xl mb-2">🏷️</span>
                        <p>Cargando plano...</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer de Opciones -->
        <div class="h-24 bg-gray-50 border-t border-gray-200 flex items-center justify-between px-6 py-6 shrink-0 z-20">
            <div id="lbl-modo" class="text-xs text-gray-400 font-medium flex items-center gap-2">
                <span class="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span>
                Modo Selección
            </div>

            <div id="footer-controls" class="flex items-center gap-4 ">
                <button id="btn-unir" onclick="setSelectionMode('unir')"
                    class="px-4 py-4 bg-white border border-indigo-200 text-indigo-600 rounded text-sm font-bold shadow-sm hover:shadow-md hover:border-indigo-400 hover:bg-indigo-50 active:scale-95 transition-all flex items-center gap-2 group">
                    <span class="group-hover:scale-110 transition-transform">🔗</span>
                    <span>Unir Mesas</span>
                </button>

                <button id="btn-separar" onclick="setSelectionMode('separar')"
                    class="px-4 py-4 bg-white border border-orange-200 text-orange-600 rounded text-sm font-bold shadow-sm hover:shadow-md hover:border-orange-400 hover:bg-orange-50 active:scale-95 transition-all flex items-center gap-2  group">
                    <span class="group-hover:scale-110 transition-transform">✂️</span>
                    <span>Separar</span>
                </button>

                <button id="btn-mover" onclick="setSelectionMode('mover')"
                    class="px-4 py-4 bg-white border border-blue-200 text-blue-600 rounded text-sm font-bold shadow-sm hover:shadow-md hover:border-blue-400 hover:bg-blue-50 active:scale-95 transition-all flex items-center gap-2 group">
                    <span class="group-hover:scale-110 transition-transform">🖐️</span>
                    <span>Mover</span>
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    (function () {
        let currentPiso = 0;
        let pisosData = [];

        // Estado de Selección
        let selectionMode = null; // null, 'unir', 'separar'
        let selectedMesas = [];

        let mesaPrincipal = null;

        // Estado Drag & Drop
        let isDragging = false;
        let dragMesaId = null;
        let dragOffset = { x: 0, y: 0 };
        let mesasChanged = false; // Para saber si activar botón guardar

        window.toggleMesasOverlay = function () {
            const overlay = document.getElementById('mesas-overlay');
            if (overlay.classList.contains('hidden')) {
                overlay.classList.remove('hidden');
                loadMesas();
            } else {
                overlay.classList.add('hidden');
                resetSelectionMode();
            }
        }

        async function loadMesas() {
            try {
                const res = await fetch('<?= base_url('api/get_pisos_mesas') ?>');
                const data = await res.json();
                //console.log(data);

                pisosData = data;

                // Default to first floor
                if (pisosData.length > 0 && currentPiso === 0) {
                    currentPiso = pisosData[0].id;
                }

                renderPisosNav();
                if (currentPiso) renderMesas(currentPiso);

                const loader = document.querySelector('.content-loading');
                if (loader) loader.classList.add('hidden');

            } catch (e) {
                console.error("Error loading mesas", e);
            }
        }

        function renderPisosNav() {
            const nav = document.getElementById('pisos-nav');
            nav.innerHTML = '';
            pisosData.forEach((piso) => {
                const btn = document.createElement('button');
                const isActive = currentPiso == piso.id;

                btn.className = `w-20 h-20 rounded-sm flex flex-col items-center justify-center text-xs font-bold gap-4 transition-all duration-200 border-2 select-none 
                ${isActive
                        ? 'bg-indigo-600 text-white border-indigo-600 shadow-lg scale-105'
                        : 'bg-white text-gray-500 border-gray-200 hover:border-indigo-400 hover:text-indigo-500 shadow-sm'}`;

                btn.innerHTML = `
                <span class="text-xl">${isActive ? '🏢' : '🏬'}</span>
                <span>${piso.nombre}</span>
            `;
                btn.onclick = () => {
                    currentPiso = piso.id;
                    // Recargar datos para tener el estado actualizado
                    loadMesas();
                };
                nav.appendChild(btn);
            });
        }

        function renderMesas(pisoId) {
            const container = document.getElementById('mesas-container');
            const bg = container.querySelector('.z-0');
            container.innerHTML = '';

            const piso = pisosData.find(p => p.id == pisoId);
            if (!piso) return;

            const mapArea = document.createElement('div');
            mapArea.className = 'relative w-full h-full z-10 bg-yellow-50/50';

            // Capa para líneas CSS
            const linesContainer = document.createElement('div');
            linesContainer.className = 'absolute inset-0 pointer-events-none z-0 file-lines-layer';
            mapArea.appendChild(linesContainer);
            piso.mesas.forEach(mesa => {

                console.log(mesa);


                const isSelected = selectedMesas.includes(mesa.id);
                const isPrincipal = mesaPrincipal === mesa.id;
                const isOcupada = mesa.estado === 'ocupada';
                const hasPadre = mesa.id_padre != null; // Es una mesa unida (hija)                

                // Capa para líneas CSS
                // Se dibuja en drawLines()
                /*
                const x1 = parseInt(mesa.x) + 32; 
                 ... moved to drawLines ...
                */

                let styles = 'bg-emerald-50 border-emerald-500 text-emerald-800 hover:bg-emerald-100 hover:border-emerald-600  shadow-sm';
                // Icono Libre (Mesa vacía / Check)
                let icon = `<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>`;
                let tienePadre = '';

                if (isOcupada) {
                    styles = 'bg-indigo-50 border-indigo-500/50 text-indigo-600  ';
                    // Icono Ocupada (Usuarios / Grupo)
                    icon = `<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path></svg>`;
                }

                if (hasPadre) {
                    // Mesa hija / unida
                    styles = 'bg-gray-100 border-gray-300 text-gray-400 opacity-80';
                    icon = '🔗';
                    // Mostrar visualmente a qué mesa está unida
                    const mPadre = findMesaById(mesa.id_padre);
                    const nombrePadre = mPadre ? mPadre.nombre : mesa.id_padre;
                    tienePadre = `<span class="absolute top-0 right-0 bg-indigo-600 text-white text-[10px] font-bold px-1.5 py-0.5 rounded-sm border border-white z-30">${nombrePadre}</span>`;

                }

                if (isSelected) {
                    styles = 'bg-indigo-100 border-indigo-500 text-indigo-700 ring-4 ring-indigo-300 scale-110 z-20';
                }

                if (isPrincipal) {
                    styles = 'bg-indigo-600 border-indigo-700 text-white ring-4 ring-indigo-300 scale-110 z-20 shadow-xl';
                }

                // Validar deshabilitado visual en modos
                let disabled = false;
                if (selectionMode === 'unir') {
                    // Si ya hay principal, las siguientes deben estar LIBRES y NO tener padre
                    if (mesaPrincipal && !isPrincipal) {
                        if (isOcupada || hasPadre) {
                            styles += ' opacity-30 grayscale cursor-not-allowed';
                            disabled = true;
                        }
                    }
                    // Si es hija, no puede ser principal
                    if (!mesaPrincipal && hasPadre) {
                        styles += ' opacity-30 grayscale cursor-not-allowed';
                        disabled = true;
                    }
                }

                if (selectionMode === 'separar') {
                    // Solo podemos separar mesas que tengan padre (hijas)
                    if (!hasPadre) {
                        styles += ' opacity-30 grayscale cursor-not-allowed';
                        disabled = true;
                    }
                }

                if (selectionMode === 'mover') {
                    styles += ' cursor-move hover:scale-105 hover:shadow-xl';
                    icon = '🖐️';
                    disabled = true; // Desactivar click normal
                }

                const el = document.createElement('button');
                el.id = `mesa-${mesa.id}`;
                el.className = `absolute flex flex-col items-center justify-center shadow-lg rounded-md w-16 h-12 transition-all duration-300 active:scale-95 border-[2px] group ${styles}`;
                el.style.left = mesa.x + 'px';
                el.style.top = mesa.y + 'px';

                el.innerHTML = `
                <span class="text-md filter drop-shadow-sm group-hover:rotate-12 transition-transform duration-300">
                    ${icon}
                </span>
                <span class="font-bold text-xs leading-none mt-1">${mesa.nombre}</span>
            ${tienePadre}
            `
                    ;

                if (!disabled) {
                    el.onclick = () => onSelectMesa(mesa);
                }

                if (selectionMode === 'mover') {
                    el.onmousedown = (e) => startDrag(e, mesa, el);
                }

                mapArea.appendChild(el);
            });

            container.appendChild(mapArea);
            drawLines(piso);
            updateStatusText();
        }

        function drawLines(piso) {
            // Buscar contenedor de líneas, si no existe, no dibujar (aunque debería existir)
            // Pero como estamos dentro de mapArea que recreamos, mejor lo buscamos o limpiamos.
            // Como renderMesas recrea el mapArea, necesitamos recrear linesContainer allí o buscarlo.
            // Solución: renderMesas crea linesContainer. Aqui solo agregamos lineas.

            // Oops, renderMesas creates linesContainer but we need reference.
            // Better: drawLines clears and fills existing container inside mapArea.
            const container = document.getElementById('mesas-container');
            if (!container) return;
            const linesContainer = container.querySelector('.file-lines-layer');
            if (!linesContainer) return;

            linesContainer.innerHTML = ''; // Clear

            piso.mesas.forEach(mesa => {
                if (mesa.id_padre) {
                    const padre = piso.mesas.find(m => m.id == mesa.id_padre);
                    if (padre) {
                        const x1 = parseInt(mesa.x) + 32;
                        const y1 = parseInt(mesa.y) + 24;
                        const x2 = parseInt(padre.x) + 32;
                        const y2 = parseInt(padre.y) + 24;

                        const length = Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2);
                        const angle = Math.atan2(y2 - y1, x2 - x1) * (180 / Math.PI);

                        const line = document.createElement('div');
                        line.className = 'absolute h-0.5 origin-left pointer-events-none';
                        line.style.width = `${length}px`;
                        line.style.left = `${x1}px`;
                        line.style.top = `${y1}px`;
                        line.style.transform = `rotate(${angle}deg)`;
                        line.style.borderTop = '2px dashed #a5b4fc';

                        linesContainer.appendChild(line);
                    }
                }
            });
        }

        // --- Drag Functions ---

        function startDrag(e, mesa, el) {
            if (selectionMode !== 'mover') return;
            e.preventDefault();
            isDragging = true;
            dragMesaId = mesa.id;

            // Calculate offset logic
            // Using scrollLeft/scrollTop of container if needed, but clientX is usually enough
            const rect = el.getBoundingClientRect();
            dragOffset.x = e.clientX - rect.left;
            dragOffset.y = e.clientY - rect.top;

            document.addEventListener('mousemove', onDrag);
            document.addEventListener('mouseup', endDrag);

            el.style.zIndex = 100; // Bring to front
            el.style.cursor = 'grabbing';
        }

        function onDrag(e) {
            if (!isDragging) return;

            const container = document.getElementById('mesas-container');
            const containerRect = container.getBoundingClientRect();

            // Calculate new position relative to container
            // Account for container scroll
            let newX = e.clientX - containerRect.left - dragOffset.x + container.scrollLeft;
            let newY = e.clientY - containerRect.top - dragOffset.y + container.scrollTop;

            // Boundaries (0 to large number)
            if (newX < 0) newX = 0;
            if (newY < 0) newY = 0;

            // Update Data
            const piso = pisosData.find(p => p.id == currentPiso);
            const mesa = piso.mesas.find(m => m.id === dragMesaId);
            if (mesa) {
                mesa.x = newX;
                mesa.y = newY;

                // Update DOM Element
                const el = document.getElementById(`mesa-${dragMesaId}`);
                if (el) {
                    el.style.left = newX + 'px';
                    el.style.top = newY + 'px';
                }

                // Redraw Lines
                drawLines(piso);

                if (!mesasChanged) {
                    mesasChanged = true;
                    updateUIButtons();
                }
            }
        }

        function endDrag() {
            if (!isDragging) return;
            isDragging = false;
            const el = document.getElementById(`mesa-${dragMesaId}`);
            if (el) {
                el.style.zIndex = '';
                el.style.cursor = 'move';
            }
            dragMesaId = null;
            document.removeEventListener('mousemove', onDrag);
        }

        async function onSelectMesa(mesa) {
            if (selectionMode === 'unir') {
                handleUnirSelection(mesa);
            } else if (selectionMode === 'separar') {
                handleSepararSelection(mesa);
            } else {
                // Modo Normal
                if (mesa.id_padre) {
                    // Si es hija, abrimos la padre
                    const padre = findMesaById(mesa.id_padre);
                    if (padre) {
                        alert(`Esta mesa está unida a ${padre.nombre}. Abriendo mesa principal.`);
                        triggerSelectMesa(padre);
                    } else {
                        // Fallback si no encontramos el padre en memoria (otro piso?)
                        // Por ahora intentamos abrirla como tal, el backend redirigirá? No, el backend espera id mesa.
                        // Idealmente buscamos el padre en API si no está local.
                        triggerSelectMesa(mesa); // Provisional
                    }
                } else {
                    triggerSelectMesa(mesa);
                }
            }
        }

        function handleUnirSelection(mesa) {
            if (!mesaPrincipal) {
                // Seleccionando la principal (Padre)
                mesaPrincipal = mesa.id;
                // No la agregamos a selectedMesas array para distinguirla
            } else {
                // Seleccionando secundarias
                if (mesa.id === mesaPrincipal) {
                    // Deseleccionar principal
                    mesaPrincipal = null;
                    selectedMesas = [];
                } else if (selectedMesas.includes(mesa.id)) {
                    // Deseleccionar
                    selectedMesas = selectedMesas.filter(id => id !== mesa.id);
                } else {
                    // Seleccionar (Validación doble por seguridad)
                    if (mesa.estado === 'libre' && !mesa.id_padre) {
                        selectedMesas.push(mesa.id);
                    }
                }
            }
            renderMesas(currentPiso);
            updateUIButtons();
        }

        function handleSepararSelection(mesa) {
            if (selectedMesas.includes(mesa.id)) {
                selectedMesas = selectedMesas.filter(id => id !== mesa.id);
            } else {
                selectedMesas.push(mesa.id);
            }
            renderMesas(currentPiso);
            updateUIButtons();
        }

        async function triggerSelectMesa(mesa) {
            toggleMesasOverlay();
            if (window.app && window.app.selectMesa) {
                await window.app.selectMesa(mesa);
            }
        }

        // --- Logic de Botones ---

        window.setSelectionMode = function (mode) {
            if (selectionMode === mode) {
                resetSelectionMode(); // Toggle off
            } else {
                selectionMode = mode;
                selectedMesas = [];
                mesaPrincipal = null;
                mesasChanged = false; // Reset cambios
                renderMesas(currentPiso);
                updateUIButtons();
            }
        }

        function resetSelectionMode() {
            selectionMode = null;
            selectedMesas = [];
            mesaPrincipal = null;
            mesasChanged = false;
            renderMesas(currentPiso);
            updateUIButtons();
        }

        window.confirmarAccion = async function () {
            const btn = document.getElementById('btn-confirmar');
            const originalText = btn.innerHTML;
            btn.disabled = true;
            btn.innerText = 'Procesando...';

            try {
                let res;
                if (selectionMode === 'unir') {
                    res = await fetch('<?= base_url('api/unir_mesas') ?>', {
                        method: 'POST', body: JSON.stringify({
                            id_principal: mesaPrincipal,
                            ids_secundarias: selectedMesas
                        })
                    });
                } else if (selectionMode === 'separar') {
                    res = await fetch('<?= base_url('api/separar_mesas') ?>', {
                        method: 'POST', body: JSON.stringify({ ids_mesas: selectedMesas })
                    });
                } else if (selectionMode === 'mover') {
                    // Recopilar posiciones actuales del piso actual
                    const currentMesas = pisosData.find(p => p.id == currentPiso).mesas;
                    const updates = currentMesas.map(m => ({ id: m.id, x: m.x, y: m.y }));

                    res = await fetch('<?= base_url('api/update_mesas_positions') ?>', {
                        method: 'POST', body: JSON.stringify({ mesas: updates })
                    });
                }

                const data = await res.json();
                if (data.success) {
                    resetSelectionMode();
                    loadMesas(); // Recargar estado completo
                } else {
                    alert('Error: ' + JSON.stringify(data.messages));
                }

            } catch (e) {
                console.error(e);
                alert('Error de conexión');
            }

            btn.disabled = false;
            btn.innerHTML = originalText;
        }

        function updateUIButtons() {
            const btnUnir = document.getElementById('btn-unir');

            const btnSeparar = document.getElementById('btn-separar');
            const btnMover = document.getElementById('btn-mover');
            const containerAcciones = document.getElementById('acciones-container');
            const lblModo = document.getElementById('lbl-modo');

            // Texto de estado
            if (selectionMode) {
                lblModo.innerHTML = `<span class="text-indigo-600 font-bold">MODO ${selectionMode.toUpperCase()}</span>`;
            } else {
                lblModo.innerHTML = `<span class="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span> Modo Selección`;
            }

            // Visual buttons
            if (selectionMode === 'unir') {
                btnUnir.classList.add('ring-2', 'ring-indigo-500', 'bg-indigo-50');
                btnSeparar.classList.add('opacity-50', 'pointer-events-none');
            } else if (selectionMode === 'separar') {
                btnSeparar.classList.add('ring-2', 'ring-orange-500', 'bg-orange-50');
                btnUnir.classList.add('opacity-50', 'pointer-events-none');
                btnMover.classList.add('opacity-50', 'pointer-events-none');
            } else if (selectionMode === 'mover') {
                btnMover.classList.add('ring-2', 'ring-blue-500', 'bg-blue-50');
                btnUnir.classList.add('opacity-50', 'pointer-events-none');
                btnSeparar.classList.add('opacity-50', 'pointer-events-none');
            } else {
                btnUnir.classList.remove('ring-2', 'ring-indigo-500', 'bg-indigo-50', 'opacity-50', 'pointer-events-none');
                btnSeparar.classList.remove('ring-2', 'ring-orange-500', 'bg-orange-50', 'opacity-50', 'pointer-events-none');
                btnMover.classList.remove('ring-2', 'ring-blue-500', 'bg-blue-50', 'opacity-50', 'pointer-events-none');
            }

            // Botón Confirmar
            const canConfirm = (selectionMode === 'unir' && mesaPrincipal && selectedMesas.length > 0) ||
                (selectionMode === 'separar' && selectedMesas.length > 0) ||
                (selectionMode === 'mover' && mesasChanged);

            let btnConfirm = document.getElementById('btn-confirmar');
            if (canConfirm) {
                if (!btnConfirm) {
                    // Crear botón confirmar dynamicamente
                    btnConfirm = document.createElement('button');
                    btnConfirm.id = 'btn-confirmar';
                    btnConfirm.onclick = window.confirmarAccion;
                    btnConfirm.className = 'ml-4 px-6 py-4 bg-green-500 text-green-50 rounded-sm text-sm font-bold shadow-lg hover:shadow-green-500/30 active:scale-95 transition-all animate-bounce-in';
                    btnConfirm.innerHTML = selectionMode === 'mover' ? 'GUARDAR UBICACIONES' : 'CONFIRMAR';
                    document.querySelector('#footer-controls').appendChild(btnConfirm);
                } else {
                    // Actualizar texto si cambia modo
                    btnConfirm.innerHTML = selectionMode === 'mover' ? 'GUARDAR UBICACIONES' : 'CONFIRMAR';
                }
            } else {
                if (btnConfirm) btnConfirm.remove();
            }
        }

        function updateStatusText() {
            // Opcional: mostrar instrucciones en UI
        }

        function findMesaById(id) {
            for (const piso of pisosData) {
                const found = piso.mesas.find(m => m.id == id);
                if (found) return found;
            }
            return null;
        }

    })();

    // Setup initial buttons
    document.addEventListener('DOMContentLoaded', () => {
        // Ya están definidos en el HTML, pero necesitamos asignarles IDs o onclicks aqui o en HTML.
        // Vamos a modificar el HTML en el siguiente paso o inyectarlo aqui si podemos, pero es mejor editar el HTML arriba.
    });
</script>