<!-- Table Selection Overlay -->
<div id="mesas-overlay"
    class="fixed inset-0 bg-black/50 z-50  hidden flex items-center justify-center backdrop-blur-sm transition-opacity duration-300">
    <div class="bg-white rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-fade-in-up transform transition-all"
        style="width: 90vw; height: 90vh;">

        <!-- Header -->
        <div
            class="h-16  from-indigo-600 to-purple-600 text-gray-500 flex items-center justify-between px-6 shadow-md shrink-0">
            <h2 class="text-2xl font-bold flex items-center gap-3">
                <span class="text-3xl">🍽️</span>
                <span>Selección de Mesa</span>
            </h2>
            <div class="flex items-center gap-4">

                <button onclick="toggleMesasOverlay()"
                    class="p-2 hover:bg-white/20 rounded-full transition-colors focus:outline-none">
                    <svg class="w-20 h-20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>

        <!-- Content -->
        <div class="flex-1 flex overflow-hidden">
            <!-- Sidebar / Floors -->
            <div class="w-[100px] bg-gray-50 border-r border-gray-200 flex flex-col items-center py-6 gap-4 overflow-y-auto z-10 shadow-inner"
                id="pisos-nav">
                <!-- Tabs generated by JS -->
            </div>

            <!-- Map Area -->
            <div class="w-[calc(100%-100px)] bg-slate-100 relative overflow-auto p-0 cursor-grab active:cursor-grabbing"
                id="mesas-container">
                <!-- Grid Background -->

                <div class="absolute inset-0 flex items-center justify-center text-gray-400 z-0 content-loading">
                    <div class="flex flex-col items-center animate-pulse">
                        <span class="text-4xl mb-2">🏷️</span>
                        <p>Cargando plano...</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer de Opciones -->
        <div class="h-16 bg-gray-50 border-t border-gray-200 flex items-center justify-between px-6 shrink-0 z-20">
            <div id="lbl-modo" class="text-xs text-gray-400 font-medium flex items-center gap-2">
                <span class="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span>
                Modo Selección
            </div>

            <div id="footer-controls" class="flex items-center gap-3">
                <button id="btn-unir" onclick="setSelectionMode('unir')"
                    class="px-4 py-2 bg-white border border-indigo-200 text-indigo-600 rounded-xl text-sm font-bold shadow-sm hover:shadow-md hover:border-indigo-400 hover:bg-indigo-50 active:scale-95 transition-all flex items-center gap-2 group">
                    <span class="group-hover:scale-110 transition-transform">🔗</span>
                    <span>Unir Mesas</span>
                </button>

                <button id="btn-separar" onclick="setSelectionMode('separar')"
                    class="px-4 py-2 bg-white border border-orange-200 text-orange-600 rounded-xl text-sm font-bold shadow-sm hover:shadow-md hover:border-orange-400 hover:bg-orange-50 active:scale-95 transition-all flex items-center gap-2 group">
                    <span class="group-hover:scale-110 transition-transform">✂️</span>
                    <span>Separar</span>
                </button>
            </div>
        </div>
    </div>
</div>

<script>
    (function () {
        let currentPiso = 0;
        let pisosData = [];

        // Estado de Selección
        let selectionMode = null; // null, 'unir', 'separar'
        let selectedMesas = [];
        let mesaPrincipal = null;

        window.toggleMesasOverlay = function () {
            const overlay = document.getElementById('mesas-overlay');
            if (overlay.classList.contains('hidden')) {
                overlay.classList.remove('hidden');
                loadMesas();
            } else {
                overlay.classList.add('hidden');
                resetSelectionMode();
            }
        }

        async function loadMesas() {
            try {
                const res = await fetch('<?= base_url('api/get_pisos_mesas') ?>');
                const data = await res.json();
                pisosData = data;

                // Default to first floor
                if (pisosData.length > 0 && currentPiso === 0) {
                    currentPiso = pisosData[0].id;
                }

                renderPisosNav();
                if (currentPiso) renderMesas(currentPiso);

                const loader = document.querySelector('.content-loading');
                if (loader) loader.classList.add('hidden');

            } catch (e) {
                console.error("Error loading mesas", e);
            }
        }

        function renderPisosNav() {
            const nav = document.getElementById('pisos-nav');
            nav.innerHTML = '';
            pisosData.forEach((piso) => {
                const btn = document.createElement('button');
                const isActive = currentPiso == piso.id;

                btn.className = `w-20 h-20 rounded-sm flex flex-col items-center justify-center text-xs font-bold gap-4 transition-all duration-200 border-2 select-none 
                ${isActive
                        ? 'bg-indigo-600 text-white border-indigo-600 shadow-lg scale-105'
                        : 'bg-white text-gray-500 border-gray-200 hover:border-indigo-400 hover:text-indigo-500 shadow-sm'}`;

                btn.innerHTML = `
                <span class="text-xl">${isActive ? '🏢' : '🏬'}</span>
                <span>${piso.nombre}</span>
            `;
                btn.onclick = () => {
                    currentPiso = piso.id;
                    renderMesas(currentPiso);
                    renderPisosNav();
                    // Si cambiamos de piso, mantenemos selección si es posible, pero simplificamos limpiando para evitar líos visuales cross-floor por ahora
                    // selectedMesas = []; 
                    // mesaPrincipal = null;
                    // updateUIButtons();
                };
                nav.appendChild(btn);
            });
        }

        function renderMesas(pisoId) {
            const container = document.getElementById('mesas-container');
            const bg = container.querySelector('.z-0');
            container.innerHTML = '';

            const piso = pisosData.find(p => p.id == pisoId);
            if (!piso) return;

            const mapArea = document.createElement('div');
            mapArea.className = 'relative w-full h-full z-10 bg-yellow-50/50';

            piso.mesas.forEach(mesa => {
                const isSelected = selectedMesas.includes(mesa.id);
                const isPrincipal = mesaPrincipal === mesa.id;
                const isOcupada = mesa.estado === 'ocupada';
                const hasPadre = mesa.id_padre != null; // Es una mesa unida (hija)

                // Si tiene padre, verificamos si su padre está en este mismo piso para dibujar alguna línea (opcional futuro)
                // Por ahora, las hijas se ven normales pero bloqueadas o con indicador

                let styles = 'bg-white border-emerald-400/50 text-gray-600 hover:border-emerald-500 hover:bg-emerald-50 ring-2 ring-emerald-100 ring-offset-2';
                let icon = '🍽️';

                if (isOcupada) {
                    styles = 'bg-red-50 border-red-500/50 text-red-600 ring-2 ring-red-200 ring-offset-2';
                    icon = '🍝';
                }

                if (hasPadre) {
                    // Mesa hija / unida
                    styles = 'bg-gray-100 border-gray-300 text-gray-400 opacity-80';
                    icon = '🔗';
                }

                if (isSelected) {
                    styles = 'bg-indigo-100 border-indigo-500 text-indigo-700 ring-4 ring-indigo-300 scale-110 z-20';
                }

                if (isPrincipal) {
                    styles = 'bg-indigo-600 border-indigo-700 text-white ring-4 ring-indigo-300 scale-110 z-20 shadow-xl';
                }

                // Validar deshabilitado visual en modos
                let disabled = false;
                if (selectionMode === 'unir') {
                    // Si ya hay principal, las siguientes deben estar LIBRES y NO tener padre
                    if (mesaPrincipal && !isPrincipal) {
                        if (isOcupada || hasPadre) {
                            styles += ' opacity-30 grayscale cursor-not-allowed';
                            disabled = true;
                        }
                    }
                    // Si es hija, no puede ser principal
                    if (!mesaPrincipal && hasPadre) {
                        styles += ' opacity-30 grayscale cursor-not-allowed';
                        disabled = true;
                    }
                }

                if (selectionMode === 'separar') {
                    // Solo podemos separar mesas que tengan padre (hijas)
                    if (!hasPadre) {
                        styles += ' opacity-30 grayscale cursor-not-allowed';
                        disabled = true;
                    }
                }

                const el = document.createElement('button');
                el.className = `absolute flex flex-col items-center justify-center shadow-lg rounded-md w-16 h-12 transition-all duration-300 active:scale-95 border-[2px] group ${styles}`;
                el.style.left = mesa.x + 'px';
                el.style.top = mesa.y + 'px';

                el.innerHTML = `
                <span class="text-md filter drop-shadow-sm group-hover:rotate-12 transition-transform duration-300">
                    ${icon}
                </span>
                <span class="font-bold text-xs leading-none mt-1">${mesa.nombre}</span>
            `;

                if (!disabled) {
                    el.onclick = () => onSelectMesa(mesa);
                }

                mapArea.appendChild(el);
            });

            container.appendChild(mapArea);
            updateStatusText();
        }

        async function onSelectMesa(mesa) {
            if (selectionMode === 'unir') {
                handleUnirSelection(mesa);
            } else if (selectionMode === 'separar') {
                handleSepararSelection(mesa);
            } else {
                // Modo Normal
                if (mesa.id_padre) {
                    // Si es hija, abrimos la padre
                    const padre = findMesaById(mesa.id_padre);
                    if (padre) {
                        alert(`Esta mesa está unida a ${padre.nombre}. Abriendo mesa principal.`);
                        triggerSelectMesa(padre);
                    } else {
                        // Fallback si no encontramos el padre en memoria (otro piso?)
                        // Por ahora intentamos abrirla como tal, el backend redirigirá? No, el backend espera id mesa.
                        // Idealmente buscamos el padre en API si no está local.
                        triggerSelectMesa(mesa); // Provisional
                    }
                } else {
                    triggerSelectMesa(mesa);
                }
            }
        }

        function handleUnirSelection(mesa) {
            if (!mesaPrincipal) {
                // Seleccionando la principal (Padre)
                mesaPrincipal = mesa.id;
                // No la agregamos a selectedMesas array para distinguirla
            } else {
                // Seleccionando secundarias
                if (mesa.id === mesaPrincipal) {
                    // Deseleccionar principal
                    mesaPrincipal = null;
                    selectedMesas = [];
                } else if (selectedMesas.includes(mesa.id)) {
                    // Deseleccionar
                    selectedMesas = selectedMesas.filter(id => id !== mesa.id);
                } else {
                    // Seleccionar (Validación doble por seguridad)
                    if (mesa.estado === 'libre' && !mesa.id_padre) {
                        selectedMesas.push(mesa.id);
                    }
                }
            }
            renderMesas(currentPiso);
            updateUIButtons();
        }

        function handleSepararSelection(mesa) {
            if (selectedMesas.includes(mesa.id)) {
                selectedMesas = selectedMesas.filter(id => id !== mesa.id);
            } else {
                selectedMesas.push(mesa.id);
            }
            renderMesas(currentPiso);
            updateUIButtons();
        }

        async function triggerSelectMesa(mesa) {
            toggleMesasOverlay();
            if (window.app && window.app.selectMesa) {
                await window.app.selectMesa(mesa);
            }
        }

        // --- Logic de Botones ---

        window.setSelectionMode = function (mode) {
            if (selectionMode === mode) {
                resetSelectionMode(); // Toggle off
            } else {
                selectionMode = mode;
                selectedMesas = [];
                mesaPrincipal = null;
                renderMesas(currentPiso);
                updateUIButtons();
            }
        }

        function resetSelectionMode() {
            selectionMode = null;
            selectedMesas = [];
            mesaPrincipal = null;
            renderMesas(currentPiso);
            updateUIButtons();
        }

        window.confirmarAccion = async function () {
            const btn = document.getElementById('btn-confirmar');
            const originalText = btn.innerHTML;
            btn.disabled = true;
            btn.innerText = 'Procesando...';

            try {
                let res;
                if (selectionMode === 'unir') {
                    res = await fetch('<?= base_url('api/unir_mesas') ?>', {
                        method: 'POST', body: JSON.stringify({
                            id_principal: mesaPrincipal,
                            ids_secundarias: selectedMesas
                        })
                    });
                } else if (selectionMode === 'separar') {
                    res = await fetch('<?= base_url('api/separar_mesas') ?>', {
                        method: 'POST', body: JSON.stringify({ ids_mesas: selectedMesas })
                    });
                }

                const data = await res.json();
                if (data.success) {
                    resetSelectionMode();
                    loadMesas(); // Recargar estado completo
                } else {
                    alert('Error: ' + JSON.stringify(data.messages));
                }

            } catch (e) {
                console.error(e);
                alert('Error de conexión');
            }

            btn.disabled = false;
            btn.innerHTML = originalText;
        }

        function updateUIButtons() {
            const btnUnir = document.getElementById('btn-unir');
            const btnSeparar = document.getElementById('btn-separar');
            const containerAcciones = document.getElementById('acciones-container');
            const lblModo = document.getElementById('lbl-modo');

            // Texto de estado
            if (selectionMode) {
                lblModo.innerHTML = `<span class="text-indigo-600 font-bold">MODO ${selectionMode.toUpperCase()}</span>`;
            } else {
                lblModo.innerHTML = `<span class="w-2 h-2 rounded-full bg-indigo-500 animate-pulse"></span> Modo Selección`;
            }

            // Visual buttons
            if (selectionMode === 'unir') {
                btnUnir.classList.add('ring-2', 'ring-indigo-500', 'bg-indigo-50');
                btnSeparar.classList.add('opacity-50', 'pointer-events-none');
            } else if (selectionMode === 'separar') {
                btnSeparar.classList.add('ring-2', 'ring-orange-500', 'bg-orange-50');
                btnUnir.classList.add('opacity-50', 'pointer-events-none');
            } else {
                btnUnir.classList.remove('ring-2', 'ring-indigo-500', 'bg-indigo-50', 'opacity-50', 'pointer-events-none');
                btnSeparar.classList.remove('ring-2', 'ring-orange-500', 'bg-orange-50', 'opacity-50', 'pointer-events-none');
            }

            // Botón Confirmar
            const canConfirm = (selectionMode === 'unir' && mesaPrincipal && selectedMesas.length > 0) ||
                (selectionMode === 'separar' && selectedMesas.length > 0);

            let btnConfirm = document.getElementById('btn-confirmar');
            if (canConfirm) {
                if (!btnConfirm) {
                    // Crear botón confirmar dynamicamente
                    btnConfirm = document.createElement('button');
                    btnConfirm.id = 'btn-confirmar';
                    btnConfirm.onclick = window.confirmarAccion;
                    btnConfirm.className = 'ml-4 px-6 py-2 bg-gradient-to-r from-green-500 to-emerald-600 text-white rounded-xl text-sm font-bold shadow-lg hover:shadow-green-500/30 active:scale-95 transition-all animate-bounce-in';
                    btnConfirm.innerHTML = 'CONFIRMAR ✅';
                    document.querySelector('#footer-controls').appendChild(btnConfirm);
                }
            } else {
                if (btnConfirm) btnConfirm.remove();
            }
        }

        function updateStatusText() {
            // Opcional: mostrar instrucciones en UI
        }

        function findMesaById(id) {
            for (const piso of pisosData) {
                const found = piso.mesas.find(m => m.id == id);
                if (found) return found;
            }
            return null;
        }

    })();

    // Setup initial buttons
    document.addEventListener('DOMContentLoaded', () => {
        // Ya están definidos en el HTML, pero necesitamos asignarles IDs o onclicks aqui o en HTML.
        // Vamos a modificar el HTML en el siguiente paso o inyectarlo aqui si podemos, pero es mejor editar el HTML arriba.
    });
</script>
</script>